name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: cuplisit
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.1'
    - uses: actions/checkout@v3
    - name: Install composer dependencies
      run: |
        composer install --no-scripts
 
    - name: Prepare Laravel Application
      run: |
        cp .env.ci .env
        php artisan key:generate
    - name: Install front-end dependencies
      run: |
        npm install
        npm run dev
 
    - name: Run Testsuite
      env:
        DB_HOST: 127.0.0.1
        DB_PORT: ${{ job.services.mysql.port['3306'] }}
        DB_USERNAME: root
        DB_PASSWORD: null
        DB_DATABASE: cuplisit
        
      run: vendor/bin/phpunit tests/
    # - name: Run php artisan 
    #   run: php artisan serve
    # - name: Run Npm
    #   run: npm run dev
    # - name: Execute tests (Unit and Feature tests) via PHPUnit
    #   env:
    #     DB_CONNECTION: sqlite
    #     DB_DATABASE: database/database.sqlite
    #   run: vendor/bin/phpunit
