name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-Lint-PHPSyntax:

    runs-on: ubuntu-latest
    strategy: 
      matrix:
        php-version: ['8.1', '8.2']

    steps:
    - name: Setup PHP
      id: setup-php
      uses: shivammatur/setup-php@v2
      with: 
        php-version: ${{ matrix.php-version }}
        tools: laravel/pint
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: composer install 
    - name: Check PHP Syntax
      uses: overtrue/phplint@${{ matrix.php-version }}
      with: 
        path: .
        options: --exclude=*.log
    - name: check code style
      run: pint --test
      
    # - name: Generate key
    #   run: php artisan key:generate
    # - name: Directory Permissions
    #   run: chmod -R 777 storage bootstrap/cache
    # - name: Create Database
    #   run: |
    #     mkdir -p database
    #     touch database/database.sqlite
    # - name: Execute tests (Unit and Feature tests) via PHPUnit
    #   env:
    #     DB_CONNECTION: sqlite
    #     DB_DATABASE: database/database.sqlite
    #   run: vendor/bin/phpunit
